version: "3.9"
services:
  base:
    image: base:latest
    build:
      dockerfile: docker/base.dockerfile

  backend:
    container_name: backend
    env_file:
      - .env
    build:
      dockerfile: docker/backend.dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  torchserve:
    container_name: torchserve
    build:
      dockerfile: docker/net-api.dockerfile
    ports:
      - "8080:8080"
